//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public string Movie_Id { get; set; }
        public string Movie_Name { get; set; }
        public string Language { get; set; }
        public System.DateTime PublishDate { get; set; }
        public string YearofRelease { get; set; }
        public string MoviePoster { get; set; }
    }
}
